# Scope Labels
"Scope: Data/Ardaas":
    - '(?:Ardaas)'
"Scope: Data/Ganj Nama":
    - '(?:Ganj\ Nama)'
"Scope: Data/Gazalaan":
    - '(?:Gazalaan)'
"Scope: Data/Jot Bigas":
    - '(?:Jot\ Bigas)'
"Scope: Data/Kabit Savaiye":
    - '(?:Kabit\ Savaiye)'
"Scope: Data/Sri Dasam Granth":
    - '(?:Sri\ Dasam\ Granth)'
"Scope: Data/Sri Guru Granth Sahib Ji":
    - '(?:Sri\ Guru\ Granth\ Sahib\ Ji)'
"Scope: Data/Vaaran Bhai Gurdaas Ji":
    - '(?:Vaaran\ Bhai\ Gurdaas\ Ji)'
"Scope: Data/Zindgi Nama":
    - '(?:Zindgi\ Nama)'
"Scope: Data/Sarabloh Granth":
    - '(?:Sarabloh\ Granth)'
