name: "Triage on Addition of Labels"
on:
  issues:
    types: [labeled]

jobs:

  triage_backlog:
    name: Triage to Backlog
    runs-on: ubuntu-latest
    steps:
      - env:
          labels: ${{ join(github.event.issue.labels.*.name, ', ') }}
          hold_label: ${{ contains( ${labels}, 'Status: Hold') }}
          todo_label: ${{ contains( ${labels}, 'Status: To Do') }}
        run: echo "${{ ${hold_label} || ${todo_label} }}"
        if: "${{ ${hold_label} || ${todo_label} }}"

      - uses: hayuna/github-project-automation-plus@v3.0.9
        with:
          project: Project Management
          column: Backlog
          repo-token: "${{ secrets.GH_PAT }}"
