name: "Issue Labeler and Triage"
on:
  issues:
    types: [opened, edited]

jobs:
  label:
    name: Label Issues
    runs-on: ubuntu-latest
    steps:
    - uses: github/issue-labeler@v2.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml
        enable-versioned-regex: 0
  
  triage_corrections:
    name: Triage to Project Correction
    needs: [label]
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.1.0
        with:
          project: Correction
          column: Triage
          repo-token: "${{ secrets.GH_PAT }}"
  
  context_stuff:
    name: testing
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump label Context
        env: 
          labelVal: ${{contains(join(github.event.issue.labels.*.name, ', '),'Scope')}}
        run: echo "$labelVal"
      - name: Dump label Context opposite
        env: 
          labelVal: ${{!contains(join(github.event.issue.labels.*.name, ', '),'Scope')}}
        run: echo "$labelVal"
  
