name: "Triage on Addition of Labels"
on:
  issues:
    types: [labeled]

jobs:

  triage_backlog:
    name: Triage to Backlog
    runs-on: ubuntu-latest
    if: "${{ contains( join(github.event.issue.labels.*.name, ', '), 'Hold' )  || contains( join(github.event.issue.labels.*.name, ', '), 'To Do') }}"
    steps:
      - uses: hayuna/github-project-automation-plus@v3.0.9
        with:
          project: Project Management
          column: Backlog
          repo-token: "${{ secrets.GH_PAT }}"
