name: "Triage"
on:
  issues:
    types: [opened, closed, assigned, reopened, labeled, unlabeled]
  label:
    types: [created, edited, deleted]

jobs:

  triage_backlog:
    name: Triage to Project Correction
    needs: [label]
    runs-on: ubuntu-latest
    steps:
      - env:
          CONTEXT: ${{ github.event }}
          
        run: echo "$CONTEXT"
      - uses: hayuna/github-project-automation-plus@v3.0.9
        with:
          project: Project Corrections
          column: Triage
          repo-token: "${{ secrets.GH_PAT }}"

  triage_project:
    name: Triage to Project Management
    needs: [label]
    if: "${{!contains(join(github.event.issue.labels.*.name, ', '),'Scope')}}"
    runs-on: ubuntu-latest
    steps:
      - uses: hayuna/github-project-automation-plus@v3.0.9
        with:
          project: Project Management
          column: Triage
          repo-token: "${{ secrets.GH_PAT }}"
