name: "Issue Labeler and Triage"
on:
  issues:
    types: [opened, edited]

jobs:
  label:
    name: Label Issues
    runs-on: ubuntu-latest
    steps:
    - uses: github/issue-labeler@v2.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml
        enable-versioned-regex: 0
  
  triage_corrections:
    name: Triage to Project Correction
    needs: [label]
    if: "${{contains(join(github.event.issue.labels.*.name, ', '),'Scope')}}"
    runs-on: ubuntu-latest
    steps:
      - uses: hayuna/github-project-automation-plus@v3.0.9
        with:
          project: Project Corrections
          column: Triage
          repo-token: "${{ secrets.GH_PAT }}"

  triage_project:
    name: Triage to Project Management
    needs: [label]
    if: "${{!contains(join(github.event.issue.labels.*.name, ', '),'Scope')}}"
    runs-on: ubuntu-latest
    steps:
      - uses: hayuna/github-project-automation-plus@v3.0.9
        with:
          project: Project Management
          column: Triage
          repo-token: "${{ secrets.GH_PAT }}"
