name: Semver

on:
  push:
    branches: [ master ]

jobs:
  bump:
    name: Bump versions
    runs-on: ubuntu-latest
    steps:
    - uses: zwaldowski/match-label-action@v1
      with:
        allowed: major,minor,patch
    - uses: zwaldowski/semver-release-action@v1
      with:
        bump: ${{ steps.bump.outputs.match }}
        github_token: "${{ secrets.GH_PAT }}"
