name: "Triage on Addition of Labels"
on:
  issues:
    types: [labeled]

jobs:

  triage_backlog:
    name: Triage to Backlog
    runs-on: ubuntu-latest
    if: "${{ contains( join(github.event.issue.labels.*.name, ', '), 'Hold' )  || contains( join(github.event.issue.labels.*.name, ', '), 'To Do') }}"
    steps:
      - uses: hayuna/github-project-automation-plus@v3.0.9
        with:
          project: Project Management
          column: Backlog
          repo-token: "${{ secrets.GH_PAT }}"

  triage_evaluate:
    name: Triage to Evaluate
    runs-on: ubuntu-latest
    if: "${{ contains( join(github.event.issue.labels.*.name, ', '), 'Score' )  || contains( join(github.event.issue.labels.*.name, ', '), '? ? ?') || contains( join(github.event.issue.labels.*.name, ', '), 'Vague') || contains( join(github.event.issue.labels.*.name, ', '), 'Question') }}"
    steps:
      - uses: hayuna/github-project-automation-plus@v3.0.9
        with:
          project: Project Management
          column: Evaluate
          repo-token: "${{ secrets.GH_PAT }}"

  triage_progress:
    needs: [triage_backlog, triage_evaluate]
    name: Triage to Progress
    runs-on: ubuntu-latest
    if: "${{ contains( join(github.event.issue.labels.*.name, ', '), 'WIP' ) }}"
    steps:
      - uses: hayuna/github-project-automation-plus@v3.0.9
        with:
          project: Project Management
          column: Progress
          repo-token: "${{ secrets.GH_PAT }}"